# Generated by Django 3.2.8 on 2022-05-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='principal',
            fields=[
                ('pname', models.CharField(max_length=25)),
                ('pusername', models.CharField(max_length=20)),
                ('ppassword', models.CharField(max_length=20)),
                ('pid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pemail', models.EmailField(max_length=35)),
                ('pmob', models.IntegerField()),
            ],
        ),
    ]
