# Generated by Django 3.2.8 on 2022-05-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('tusername', models.CharField(max_length=20)),
                ('tpassword', models.CharField(max_length=20)),
                ('tgender', models.CharField(max_length=20)),
                ('tdob', models.DateField()),
                ('tmob', models.IntegerField()),
                ('tage', models.IntegerField()),
                ('tsub', models.CharField(max_length=20)),
            ],
        ),
    ]
