# Generated by Django 3.2.8 on 2022-05-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_stuent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stuent',
            new_name='student',
        ),
    ]
