# Generated by Django 3.2.8 on 2022-05-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_stuent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slno', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
